### ISSUE TITLE
Incorrect counting of mentions (Discord) QoL

### ISSUE THREAD

**Issue by dcaldr** [mlomb/chat-analytics#1]
This is an amazing app, your work motivated me to start learning about language parsing and processing. 

But I've noticed that in (Discord) report &rarr; Interaction &rarr; Most Mentioned has mentions that doesn't exist and were counted from  links in send messages. 
ie. message:
> have you seen this: [https://medium.com/@mostsignificant/3-ways-to-parse....](https://medium.com/@mostsignificant/3-ways-to-parse-command-line-arguments-in-c-quick-do-it-yourself-or-comprehensive-36913284460f) 

will count mostsignificant as a mention 
I'm unable to find solution nor problematic function (I've never much used javascript/typescript). I don't find it problematic, it is just a feedback.

**Comment by mlomb** [comment]
Hi thanks for the feedback and sorry for the late reply.
This was caused by the Tokenizer not allowing `@` in the URLs.
It should be fixed now.
