### ISSUE TITLE
[Feature request] Store dates and times as UNIX timestamps

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#10]
This relates to one of the items listed in TODO.md

https://github.com/mlomb/chat-analytics/blob/554620139acb80964c5ae2748b6f025e6fc65490/TODO.md#L13

---

Currently, dates and times are stored as the number of days since the first date included in the report (dayIndex) and the number of seconds into that day (secondsOfDay).

https://github.com/mlomb/chat-analytics/blob/44823587ff7007810b324452cee2db06a2435a31/pipeline/serialization/MessageView.ts#L8-L9

Of course, these values are timezone-specific, resulting in the need for a config option as listed in the TODO above. However, storing these as a timestamp will allow the date and time shown to the user to be adjusted based on the timezone suggested by their own browser. Most platforms will export dates and times using timestamps anyways, so maintaining this will slightly improve the speed a report can be generated and the maintainability of the code since the timestamp doesn't have to be converted to a `dayIndex` and `secondsOfDay`

---

Now, I understand that the purpose off `dayIndex` and `secondsOfDay` is to improve compression, but I'd argue a UNIX timestamp could be compressed just as well, if not better. First, I'll talk theoretically, then I'll use more realistic estimates.

Most platforms are designed to support dates from between 01/01/1970 and 19/01/2038, so the theoretical max size of dayIndex is 24855 which would take $log_2 24855 \approxeq 15$ bits to store. There are $60\cdot60\cdot24 = 86400$ seconds in a day which takes $log_2 86400 \approxeq 17$ bits to store, as correctly used below.

https://github.com/mlomb/chat-analytics/blob/44823587ff7007810b324452cee2db06a2435a31/pipeline/serialization/MessageSerialization.ts#L31

This adds up to make 32 bits, which is the same number of bits used to store UNIX timestamps. Which makes sense, since they're storing roughly the same information.

Now, realistically, users usually only have something like 3 years worth of data included in a report, which is 1095 days. This would make `dayIndex` require $log_2 1095 \approxeq 11$ bits and 28 bits once you include `secondsOfDay`. In contrast, a UNIX timestamp is essentially a 'secondIndex', so would only require $log_2(1095\cdot86400) \approxeq 27$ bits. Of course, this is a small difference, but it shows that UNIX timestamps would never require more bits to store, but can sometimes use less. This is because it can take advantage of the remainder bits from `dayIndex`.

---

I would still suggest that a config option be included, because sometimes the user generating a report may not want results to be shown differently based on the timezone the report is shown in since this could cause confusion. However, for most users I don't think this would be an issue.

##### PS: I don't know why I put so much effort writing this issue considering I already discussed this with mlomb in DMs lol

**Comment by mlomb** [comment]
Problems I see using timestamp instead of indexes hardcoded with a single timezone at generation time:
* Start and end dates may differ depending on the timezone, so reports may span for longer/shorter
* Since now users have different cuts for when days/weeks/months start, they will definitely see different numbers in the reports and may be confused
* Some big changes may be needed to allow for non fixed start/ends in reports

Also I think it is OK as it is, always better to work with day-month-year instead of timestamps and dates.
