### ISSUE TITLE
Discord - Locally stored users profile pictures not working

### ISSUE THREAD

**Issue by livingflore** [mlomb/chat-analytics#106]
If export by DCE was done with media from channels being stored locally (`--media true`), you wouldn't be able to see users profile picture as report being generated with [validation of URL](https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/pipeline/parse/parsers/DiscordParser.ts#L99). I assume it would be possible to use profile pictures which being stored locally if report.html and media folder are in same directory, but if they are not - simply fall back to default avatar (discord icon).

**Comment by HopperElec** [comment]
Not a fix, but you forgot to leave `https://` at the start of the link you provided so it's acting as a relative link which doesn't work 😉[Correct link](https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/pipeline/parse/parsers/DiscordParser.ts#L99)

**Comment by livingflore** [comment]
> Not a fix, but you forgot to leave `https://` at the start of the link you provided so it's acting as a relative link which doesn't work 😉[Correct link](https://github.com/mlomb/chat-analytics/blob/055c68c78e12c6e3f32cb9137135e426c49a64bf/pipeline/parse/parsers/DiscordParser.ts#L99)

sry firefox moment

**Comment by mlomb** [comment]
Hey @livingflore can you test in the PR link if the avatars have the correct path?

https://pr-107.chat-analytics.pages.dev/demo

**Comment by livingflore** [comment]
> Hey @livingflore can you test in [the PR](https://github.com/mlomb/chat-analytics/pull/107) link if the avatars have the correct path?
> 
> https://pr-107.chat-analytics.pages.dev
> 
> Edit: for context, we talked a bit on Discord, we concluded to use the path of the avatars if available.

yep, works perfect, thank you!
