### ISSUE TITLE
cant install the chat analytics package

### ISSUE THREAD

**Issue by Tom28281** [mlomb/chat-analytics#117]
Whenever I try to use this via cmd, it tells me it needs to install chat-analytics@1.1.1. I type y but nothing happens
here is my most recent attempt:

Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>npx chat-analytics
Need to install the following packages:
chat-analytics@1.1.1
Ok to proceed? (y) y

C:\Windows\System32>npx chat-analytics --version
Need to install the following packages:
chat-analytics@1.1.1
Ok to proceed? (y) y

C:\Windows\System32>

**Comment by mlomb** [comment]
Hey!
I have been able to reproduce the issue (also with older versions), I will look into it!

**Comment by Tom28281** [comment]
thank you!
