### ISSUE TITLE
Report cannot be opened. Stuck at "Loading, please wait..."

### ISSUE THREAD

**Issue by jralduaveuthey** [mlomb/chat-analytics#121]
When I create the report directly with the tool, it does work and I can see it on the browser, but when I try to open it afterwards or I share it with other people, it keeps appearing the loading message and nothing ever appears.

**Comment by hopperelec** [comment]
Sounds like you're trying to use the blob link to re-open it or share it. The blob link is just a temporary link created by your browser to temporarily let you access it. To re-open it or share it, you need to download the report.

**Comment by jralduaveuthey** [comment]
Nop. I am trying to open the html file that i have downloaded after clicking "Download Report"

**Comment by jralduaveuthey** [comment]
also fyi, i am running the webapp locally. I am not using the already deployed version. in case it makes a difference

**Comment by mlomb** [comment]
Can you show if the console prints out an error in the "Loading, please wait..." screen?

**Comment by jralduaveuthey** [comment]
What console do you mean?
The HTML should be able to open only with the browser right? I am not
trying to open the script with any script,...

**Comment by hopperelec** [comment]
The browser has a console in the developer tools, the same pane which opens if you use "Inspect element" or press F12
