### ISSUE TITLE
Cannot parse discord export file.

### ISSUE THREAD

**Issue by iddqdidkfa12** [mlomb/chat-analytics#123]
![image](https://github.com/user-attachments/assets/e97a3dda-d012-484e-8c33-1b81f0deb0ab)

error parsing file "University of Michigan - 💬General Discussion💬 - politics [1079885093784518716].html":

Expected {

**Comment by hopperelec** [comment]
You need to use a JSON file, not an HTML file

**Comment by iddqdidkfa12** [comment]
you are right i should have followed the direction.

**Comment by mlomb** [comment]
We should hint the user if the file name ends with ".html"
