### ISSUE TITLE
Discord emotes/emojis with the same name get mislabeled/counted.

### ISSUE THREAD

**Issue by uhtmilkshake** [mlomb/chat-analytics#124]
Basically, take this scenario:
message 1: ":duckHey:" (looks like a white duck waving)
message 2: ":duckHey:" (looks like a green duck waving)
when both are processed, it counts both emotes as the same one becauase they have the same name but they're not the same emote.
it counts n.2 as n.1, i think because of the way it just keeps tracks of emotes.

I think because of how [processEmoji](https://github.com/mlomb/chat-analytics/blob/e09cda3267c683ae44fdfc73aa718870a15554f2/pipeline/process/MessageProcessor.ts#L180C5-L180C17) seems to use the emote's name instead of its ID to process it.

**Comment by mlomb** [comment]
We are indeed using the name of the emoji as identifier. We could concatenate the platform ID to the identifier but it would cause other problems too. IIRC, the ID is not always available for emojis. So we would split emojis in two: the ones with the ID concatenated and the ones without. I think this is a worse situation than collapsing two with the same name into one, which makes somewhat more sense.
