### ISSUE TITLE
[Refactor] Create a new progress as part of downloadFile

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#14]
Whenever a file is being downloaded, a new progress is created to display it with the title always being the same "Downloading file" and the subject always being the filename which downloadFile can easily extract from filepath. For example, here is an extract from DatabaseBuilder where 4 different files are downloaded. Only 3 of them use progress.new, but it seems reasonable to show a progress for "lid.176" too.

https://github.com/mlomb/chat-analytics/blob/554620139acb80964c5ae2748b6f025e6fc65490/pipeline/process/DatabaseBuilder.ts#L85-L120

So, I think it would make sense to create this progress as part of downloadFile

https://github.com/mlomb/chat-analytics/blob/554620139acb80964c5ae2748b6f025e6fc65490/pipeline/File.ts#L29-L45

**Comment by mlomb** [comment]
The "lid.176" is being loaded in here, using `downloadFile`.
https://github.com/mlomb/chat-analytics/blob/554620139acb80964c5ae2748b6f025e6fc65490/pipeline/process/FastTextModel.ts#L24-L26

See the PR for more info.
