### ISSUE TITLE
[Discord][Feature request] Use a bot for live updates

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#20]
I think it would be quite nice to be able to host a website which uses chat-analytics to share analytics about a guild. This is already possible by just generating a report using all the channels in the guild and hosting the report, but a Discord bot could be used to live-update the analytics too.

One downside to this idea is that it could encourage spam if people want to show on the page, but I don't think that would be for chat-analytics to worry about and instead the moderators of the guild it is being used (the website wouldn't necessarily need to be public anyways and be made accessible only to moderators).

I'd imagine the main issue implementing this wouldn't be creating the bot but instead how to handle the database and compression. However, compression is most important for downloading and sharing the report with others, but if the data is being stored on a web server then the data could be kept server-side and the report would be dynamically generated depending on what the client is viewing. If doing this, it might also make sense to use a SQL database for storing the data so the server can request only the data needed for an individual page on the report.

**Comment by mlomb** [comment]
A cron job could download the chats with DCE (with the CLI) and run the generation process. Currently this may be possible using browser emulation, but it is really annoying.

We may want to support NodeJS in the future and make it a library, but I dropped the idea multiple times.
Having it running in NodeJS would also mean we can test better.
