### ISSUE TITLE
[Feature request] Highest/lowest sentiment messages

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#25]
Similar to 'Top reacted message', it would be cool to have a list of the most positive/negative messages based on sentiment

**Comment by HopperElec** [comment]
It may actually be more useful to do it on conversations instead of individual messages, since sentiment often depends on context and because it will include more data theoretically making it more accurate

**Comment by mlomb** [comment]
It is a good idea however messages are not stored in a readable format, for example in the "Most reacted messages", it looks weird already, I dont know...
Even less showing conversations imo

**Comment by mlomb** [comment]
Since we can't show the full message (and conversation) or a link to it, I'll close this issue as wontfix for now.
