### ISSUE TITLE
Most positive/negative users based on sentiment

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#26]

**Comment by mlomb** [comment]
Totally doable! I think it should be done in the `SentimentStats` block and similar to how `authorsReplyCount` works in the `InteractionStats` block.

Probably we want a dropdown in the title, something along the lines "Most [positive, negative] authors", also probably changing the color of the bars accordingly :)

**Comment by HopperElec** [comment]
Instead of a positive/negative dropdown, I think there should be a dedicated icon for changing the direction of the sort. This icon could be used elsewhere like:
- 'Messages sent by channel' to switch to showing the channels with the _least_ messages, which could be useful for identifying stale channels that an owner may want to delete
- 'Emojis used in [text / reactions]' to switch to showing the _least_ used emojis. This is only really useful for custom emojis, but can again be used for identifying pointless emojis that an owner may want to delete. This is especially useful since Discord servers only have a limited number of custom emoji slots, so if an owner wants to add a new one they may need to find one to replace
- 'Messages sent by author' to switch to showing the authors who have sent the _least_ messages. This might be useful for small private servers where owners only want to keep active users. It is also useful for staff applications, as an owner could reject a user's application if they aren't active enough

**Comment by HopperElec** [comment]
I'm actually not sure how to calculate this without producing biases. If you just sum all the sentiments for every message an author has sent, it would pretty much just be the same as 'Messages sent by author' saying the most active authors are more positive than less active authors. If you take the average sentiment across every message an author has sent, it would be very biased towards authors who have sent fewer messages so less data is available for them.
I think we'd have to calculate the average but only for authors who have sent a minimum number of messages (either a fixed threshold such as 1000 messages, or a percentage of other authors such as top 20% of authors)

**Comment by HopperElec** [comment]
Just thought- this could be done for channels too, rather than just users. This should be an(other) dropdown

**Comment by mlomb** [comment]
I'll close this issue due https://github.com/mlomb/chat-analytics/issues/56#issuecomment-1452488531.
I'll also open a new issue with the icon #63
