### ISSUE TITLE
[Feature request] Estimated time remaining when generating report

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#27]
Generation time is already being tracked, and combined with file sizes, number of messages and average time spent parsing each message, it should be possible to estimate how long it will take to generate a report

**Comment by mlomb** [comment]
I don't think people will care about this, also you can see the progress in MB per file and I think it is enough

**Comment by HopperElec** [comment]
That's only per file though. At the very least, I think there should be an indicator for how many files remain
