### ISSUE TITLE
[Feature Request] RegEx in language filter

### ISSUE THREAD

**Issue by mmmro** [mlomb/chat-analytics#30]
This might already be possible but id like the ability to use a regular expression to have a more customized filtered search when looking up the most used words.

**Comment by mlomb** [comment]
@mmmro could you give an example regex you would like to search for?

**Comment by HopperElec** [comment]
@mlomb It would be useful for looking for words starting or ending with the filter, instead of just containing. It's would also be useful for searching for numbers using \d

**Comment by mmmro** [comment]
@mlomb my original post was worded poorly, i should have said id like the ability to customize the stopwords. An example of a search i would do wouldnt be for any specific word but to exclude specific words like 'yo', 'lol', 'wtf' etc. Something like -E '\b(?:(?!yo|lol|lmao|wtf|haha)\b\w+)\b'

**Comment by HopperElec** [comment]
@mmmro I don't think it was worded poorly, you were just more broad which in my opinion is better, but this is another use-case for regex-filtering
