### ISSUE TITLE
Allow quicker navigation of the generation instructions (primarily for development or debugging)

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#31]
I find it mildly tedious having to go through the generation instructions every time I make a minor change that I want to quickly test or debug.

It would be useful to include sample exports which can quickly be used from the home page (if isDev). Having standardized exports is also useful for ensuring consistency between updates (for example, ensure an update didn't change the number of messages counted for whatever reason). It's also useful for people like me who mostly just uses one of the supported platforms, so doesn't have much data to use for testing, but would still like to test or work on other platforms. Finally, these sample exports could also be used for the demo(s), allowing developers to update the demo(s) to match changes.

For when a different report does still need to be uploaded, the 'Export your chats' window could be skipped, or have the 'Continue' button moved further up.

During stages 1, 2 and 3, everything needed (other than the exports) could start getting downloaded. During stage 3, uploaded exports could also start being parsed.

Finally, and this one may also apply to non-developers, once files are uploaded, the 'Generate report!' button should be automatically highlighted so that you can just press 'Enter' to continue.

**Comment by HopperElec** [comment]
I forgot that was a thing, I haven't actually tried it yet, I'll try that now!
I think all of my suggestions still apply, though, because there are other reasons a sample report would be useful for developers and the other suggestions apply to other users too.

**Comment by HopperElec** [comment]
Just tested it, and yes that's really useful! However, I don't think it would work if I was needing to test changes to the database

**Comment by HopperElec** [comment]
Only just realised that such a thing actually used to exist already https://github.com/mlomb/chat-analytics/commit/4b85eea176f3342381d48348f429a46b840a96d2 What was the reason this was removed?

**Comment by mlomb** [comment]
The description of the commit says
> node is no longer supported

I dropped support for Node since it was a pain, but it is in the plans to add it again

**Comment by HopperElec** [comment]
Oh, sorry, I didn't notice that 😅

**Comment by HopperElec** [comment]
Keeping the demo up-to-date is no longer an issue as of https://github.com/mlomb/chat-analytics/commit/999dceb282162deddcc9b2bc803f58d389a055bf however this does not include sample reports for platforms other than Discord and is not useful for testing since it only applies after it has been pushed to GitHub so I still think some sort of sample reports would be useful

**Comment by mlomb** [comment]
A few artificial samples are now available in `tests/samples`, though I agree that we _should_ have demos in the CI I think its not worth it.
Debugging the database generation is a bit annoying but we can run the code using tests, not great, not terrible.
Will close as notfix
