### ISSUE TITLE
Inconsistency with author/channel dropdown

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#33]
In the 'Messages' tab, 'Messages sent by author' and 'Messages sent by channel' are separate cards.
However, in the 'Emojis' tab, 'Emojis sent by author' and 'Emojis sent in channel' are one card with a dropdown, as with 'Authors that get the most reactions' and 'Channels that get the most reactions' in the 'Interaction' tab.
I'm not sure which of these formats is better, but I think it would be best to stick to one.

**Comment by mlomb** [comment]
I did it this way because I think 'Messages sent by author' and 'Messages sent by channel' are both relevant to a user. 'Emojis sent in channel' I think its less relevant and don't deserve its own card.
