### ISSUE TITLE
last day cuts off graph

### ISSUE THREAD

**Issue by JustAnOkapi** [mlomb/chat-analytics#41]
If you have data that goes to for example the 7th inclusively, the graph only shows up to the 6th.
![28E62A7E-4558-4B89-88DF-B09057ED1CD8](https://user-images.githubusercontent.com/39418801/212570866-a6f3a3a0-4777-4557-9b86-65b2eeb99af6.jpeg)
 in example photo you can see a very small sliver of 1px of the 7th day on the right.

**Comment by mlomb** [comment]
Thanks! Apparently Amchart's `zoomToDates` is `[start, end)` and not `[start, end]`
