### ISSUE TITLE
[Feature request] Skip export-specific errors when generating reports

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#42]
If there is an error parsing an export during the generation process, that export should just be skipped with something to indicate the error (such as an error symbol next to it with details if you hover over it)

**Comment by mlomb** [comment]
I prefer to fail altogether, it is rare to have a corrupted file and the user can try again excluding that file.

I noticed we are not reporting errors back to Plausible, so I added that here: https://github.com/mlomb/chat-analytics/pull/53/commits/719c77a5fcd58839833dca9a75b3049b4bd48cc3. We may want to add more debugging info to that later on.
