### ISSUE TITLE
[Discord][Feature request] Expand emoji usage list

### ISSUE THREAD

**Issue by Galo223344** [mlomb/chat-analytics#5]
Hello! I have to say that this is a fantastic tool, especially for solving one's need for statistical data.

Recently, I've run out of custom emoji slots in my Discord server so I wanted to remove the least used ones. I tried using this tool since no other tool had historical or reaction data, but I ran into the problem that it only shows the most used emotes. So I'd be very grateful if the functionality of expanding the list to show all emotes was added or alternatively, a button to inverse the sorting of the list (Or all lists, for that matter).

Thanks.

**Comment by HopperElec** [comment]
I imagine the reason extensive lists aren't shown is to reduce the amount of data that needs to be stored in the export, since mlomb intends on keeping it around 100MB. Config options are in TODO.md, and I've suggested that more config options could be added to allow customization of which data is included in the export. This is a perfect example of why this would be useful!

**Comment by Galo223344** [comment]
I'm fairly certain that all the emoji usage data is available in the export, as I can filter by the name of the emoji and it'll appear regardless of its in the top 10 or not.
Also, from what I've seen Discord exports don't really seem to go past like 5 megabytes 🤔 (Though that may be because I haven't tried it on any big big servers yet)

**Comment by HopperElec** [comment]
iirc, my Discord export accumulated to 3GB. This came from a mixture of
servers I own, group chats I’m in and DMs with some of my friends, but keep
in mind that I only get like 20 messages in total per day on average and
some servers get that many every second

**Comment by Galo223344** [comment]
Oh, by exports I meant reports generated by the chat analytics. Yes,
discord exports can get kinda big. But I haven't tried it on big servers
due to fear of getting my account locked.

**Comment by HopperElec** [comment]
Correction to my last message (can’t edit on mobile for some reason), idk where I got those numbers from lol. My export was 300MB and apparently (though this doesn’t sound right at all) I receive 480 total messages on average per day. But still, some servers get that many per minute, so their export would be significantly bigger.

**Comment by HopperElec** [comment]
Oh right. Well that makes sense, because as I say mlomb has made a good effort to significantly compress the ChatAnalytics exports, I assumed only storing top emojis would be one of those compression methods but I guess not

**Comment by mlomb** [comment]
Everything except words (which are cut if there are more than 100k) are stored completely, so it should be possible to see the least used emojis (also links, reactions, etc).

I gave it a try but as I was suspecting we get all emojis used once, so it's not very useful.

![image](https://user-images.githubusercontent.com/5845105/210449626-f8e81218-8d34-4619-8cde-43d8f12011b1.png)

If you really want to know, you can (using a local build of chat-analytics) print the `entries` variable in [MostUsed.tsx](https://github.com/mlomb/chat-analytics/blob/44823587ff7007810b324452cee2db06a2435a31/report/components/viz/MostUsed.tsx), and index `useDataProvider().database.emojis`.

**Comment by HopperElec** [comment]
There might not be an obvious reason it's useful, but is there really a reason not to if the data's already there? If it's just the singular emojis you don't like, could you not just set a minimum 'Times used' for an emoji to be shown?
