### ISSUE TITLE
Error message when running locally on linux

### ISSUE THREAD

**Issue by spaskob** [mlomb/chat-analytics#61]
Tried compiling a report locally using the CLI:

`npx chat-analytics -p discord -i <json_glob>  -o report.html`

And received the following error:

```
npx: installed 38 in 3.662s
Unexpected token '?'
```

The report gets generated successfully using the online app.

**Comment by mlomb** [comment]
Which node version are you using (`node -v`)?
The CI uses v16 and my machine v18; maybe you have v14? (though it should work)

**Comment by spaskob** [comment]
Thanks for the quick reply @mlomb !
Indeed, I upgraded node to v16 and this solved the problem.
Note that v18 did not work on my linux distribution (mint) due to a GLIBC glitch:

`node: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by node)`

**Comment by spaskob** [comment]
My node was v12.
