### ISSUE TITLE
Message statistics mostly blank.

### ISSUE THREAD

**Issue by stylinnile** [mlomb/chat-analytics#62]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/51105716/222260615-d54496fb-7a50-4bbc-a88b-d667ae455f09.png">
LMK if theres more information I can/I need to provide! :)

**Comment by stylinnile** [comment]
Discord, using DiscordChatExporter v2.39.0

**Comment by mlomb** [comment]
I tried using DCE v2.39.0 and it seems to work. Could you give me more details? Like:

* It was a server or a DM?
* If it was a server, it was a text channel, voice channel or some other kind of channel
* What language(s) is being used in text messages?

Something seems really off 😢

**Comment by stylinnile** [comment]
It's in a server, text channel, and in english.
I made a test channel and put a few messages in and got it to replicate. I can zip and attach the files here if that works.

**Comment by mlomb** [comment]
Yes please send it!

**Comment by stylinnile** [comment]
[files.zip](https://github.com/mlomb/chat-analytics/files/10865498/files.zip)

**Comment by mlomb** [comment]
It seems `content` is empty for all messages, maybe a bug in DCE?

**Comment by mlomb** [comment]
This is just a theory, are you using a bot account? Popular bots are no longer allowed to read messages I think

**Comment by stylinnile** [comment]
It was a bot I made through the developer portal. I didn't have the checkmark to read content enabled. I think it's working now, thanks for the help!
