### ISSUE TITLE
I cannot reduce the timeline from the left on Brave

### ISSUE THREAD

**Issue by kkanoee** [mlomb/chat-analytics#68]
GM guys.

Sick tool, I have a small issue, I cannont reduce the timeline from the starting days on brave: 
![image](https://user-images.githubusercontent.com/31211058/225035228-159375a3-073c-40cb-8e5c-11209ce9962a.png)

It works on opera tho I just tried. Have a nice day :)

**Comment by mlomb** [comment]
Searching the AmCharts repo, seems that it is a general problem: https://github.com/amcharts/amcharts5/issues/845#issuecomment-1462204728 and can't be fixed by them

😢
