### ISSUE TITLE
[Feature request] User aliases

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#7]
Many people use alt accounts, and if you're trying to compare a few specific users who use such alt accounts you might want to combine the data (such as messages sent by author, emojis sent by author, conversations started, authors that reply the most messages...) for each of their accounts. This could be implemented as a config option for generating the report, but since this data exists already (i.e. it can be manually compared, but this isn't ideal) it could be something selected while viewing the report.

**Comment by mlomb** [comment]
It is doable but we would have to design and implementa a UI only for combining authors, and significantly change how the counts are handled in the backend.

Also personally I don't think many people really use alt-accounts, and if the do probably is to separate college, work and personal life and use different servers on each, so no need to aggregate them.

**Comment by HopperElec** [comment]
Fair enough. All I'd say is for
> and significantly change how the counts are handled in the backend.
I don't think this would be too much of an issue if it was "something selected while viewing the report."
