### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by larueli** [mlomb/chat-analytics#73]
Hello !

It would be nice to have a ready to use docker image.

If you agree, I can create a PR with a Dockerfile and github actions to build on every push on main and tags and push to the github registry.

Waiting for your green light or any remarks !

**Comment by mlomb** [comment]
Sure! Go ahead! It would be better if it is in every release instead on every push, like the npm package

**Comment by larueli** [comment]
Just to be clear (linked to #74), I was at first speaking about a web usage (which is the way I use it), do you want a docker image for the web or the cli (or two image for both) ?

**Comment by mlomb** [comment]
Sorry, I understood you wanted a Docker image for the CLI. I don't think many people will want to host the app themselves, they would just use the online app.
If someone wants to use the CLI, it makes sense since some people may not want to install NodeJS just to use chat-analytics

**Comment by HopperElec** [comment]
I think it's a good idea to make it as easy as possible for people to host the app themselves. It is useful for if the official app has downtime (or is taken down completely for whatever reason), or just for people with privacy concerns

**Comment by larueli** [comment]
Yeah, my goal is to make this app selfhostable in a fully disconnected environment.

**Comment by mlomb** [comment]
I agree with you that self hosting should be an option. I added a Dockerfile and automated builds. You can find them [here](https://hub.docker.com/r/mlomb/chat-analytics/tags).

Thanks for raising the issue and pinging me :)
