### ISSUE TITLE
Call statistics

### ISSUE THREAD

**Issue by Korne127** [mlomb/chat-analytics#76]
Hey; this is an amazing tool and it's really great to look at all the stats. While using it, I've thought that it could be a great addition if it also supported call statistics.
At least the discord exports saves the beginning and ending time of each call (in DMs & group chats). That could be parsed as well and stats about it could be displayed in a new tab.

I'd imagine it to be similar to the Message statistics, just using the call information instead of the message information:
- The time of calls spent over the time by month / week / day (could be used in the same way as Messages sent over time) as the main graph
- Activity by week day & hour (split / heat map) (could also work in the same way as the message activity, just using the time on call per day instead of messages per day as the base data)
- Call statistics (such as the Message statistics in the message stats) could be
  - Total amount of calls
  - Total time of all calls
  - Average duration of a call
  - Median duration of a call
  - Three out of four calls were shorter / longer than
  - Longest call
  - Amount of calls longer / shorter than e.g. an hour
  - Total amount of messages sent during calls
  - Average amount of messages sent during a call
  - Average amount of calls per month
  - Average time between calls
  - Median time between calls
  - Most active… (used just like the message pendant using call time instead of the amount of messages)
    - year ever
    - month ever
    - day ever
- Duration of the calls (could be a chart similar to Time between sending and editing, showing how long the calls typically are)
- Total amount of messages sent during calls / Average amount of messages sent during a call by author (could be like the Messages sent by author part; maybe also split into an "amount of messages" and a "% of messages" part like the Edited messages by author part)
- Amount of calls / Total time of calls by call starter (could work in the same way as Messages sent by author)

All these statistics and graphs could also be filtered by the Call starter (or Call author), meaning the person who started the call. This could also be done just as in the message tab where you can filter all the data by the message author(s).

What do you think about this?

**Comment by mlomb** [comment]
Hey! You put a lot of tought into this! You are right, call stats would be a great addition to chat-analytics!

Since I rerely use direct or group calls, I don't have a good export with lots of calls
It should be possible to implement this without any major changes 😄. If you want to give it a try, I'm open to a PR

**Comment by HopperElec** [comment]
I have quite a few DMs and group chats with lots of calls, so I'd be happy to obfuscate them and provide them to be used for testing. I could blank out all the user information (but maintain some sort of unique ID) and message content. iirc, calls are treated as messages, so if just have to be careful not to competent clear the message content of those. Would this cause any issues?

**Comment by Korne127** [comment]
Thanks for the quick response :)
I'm glad that you agree that it would be a nice addition :D
About a pull request: I'd like to try to look into it and add it by myself.
My lectures are starting in three days though (and I need to do some planning before that), and since I haven't really looked into the source code yet (I just found this project a few days ago), I just can't exactly promise how quick I'll be able to find my way around and implement that all.
I have quite some chats with calls to potentially test that with, but I think that more exports can still help to test. I guess you could replace user ids and contents as you said and just provide extracts out of the reports.

**Comment by mlomb** [comment]
Nice! There is no rush, I'm in the middle of the semester right now too.

Yes I agree adding samples here might be a good idea, maybe even create a script that does that automatically

**Comment by HopperElec** [comment]
Hopefully I've obfuscated it enough 😅 For some reason you can't attach JSON files to GitHub issues, but you are able to attach ZIP files and it is quite large (well, 4MB) anyways so I've just zipped it.
[Sample group chat.zip](https://github.com/mlomb/chat-analytics/files/11276728/Sample.group.chat.zip)

**Comment by Laiteux** [comment]
That would be insane.

**Comment by SeymourGx** [comment]
Apologies for the bump, but I thought I'd voice some support for this suggestion as well! This is the exact feature I downloaded the app hoping for -- I fell in love with all the other features, to be sure, but this was my primary use case. Call history isn't natively supported by Discord, so for someone you may have tens or hundreds of thousands of messages with, finding logs of or statistics pertaining to your many calls is quite difficult.
A section or sub-section for call history/statistics would be thoroughly appreciated. Thank you for maintaining this wonderful tool!

**Comment by mlomb** [comment]
👀 I started working on this!

I'll kindly ask you to try your exports once the report UI is ready, for errors and feedback
Soon™

**Comment by mlomb** [comment]
I think the new calls section is ready to be tested, anyone want to give it a shot?
Use https://pr-88.chat-analytics.pages.dev, currently Discord and Telegram have calls support

**Comment by SeymourGx** [comment]
It appears to work as intended! I've tested this on the beta site linked, using a few months' worth of Discord DMs between myself and another user (50k+ messages). The other sections still function as normal, and the results for the call section were pretty interesting to me. Here's a copy of what it looks like for anyone else curious as to the new feature:
![image](https://github.com/mlomb/chat-analytics/assets/51757397/1c8c882d-4c3b-47bd-938c-0882805ed755)
No bugs to report or feedback at this time. Thanks so much, @mlomb !

**Comment by mlomb** [comment]
Merged! Not all stats that @Korne127 suggested have been implemented, I'll leave some for a future update

https://github.com/mlomb/chat-analytics/blob/7722e120395028f706262115ca62c11ed73e491e/docs/CHANGELOG.md?plain=1#L3-L10
