### ISSUE TITLE
DST in Telegram exports

### ISSUE THREAD

**Issue by vignakke** [mlomb/chat-analytics#79]
Hello, I get this error when I wait for the report to be generated, a friend told me that the cause might be the summer/winter time change if that helps.

_Error parsing file "result.json":

MessagesInterval can only be extended to the future_

**Comment by mlomb** [comment]
Good catch!
Yes problably the cause is summer/winter time. Do you have a small report so that we can reproduce the problem?

**Comment by vignakke** [comment]
hi, no I don't have a small report, the report I wanted to upload is 180mb 
i have telegram in english, and timezone is utc+01:00

**Comment by HopperElec** [comment]
Could you produce a minimal reproducible example? That is, remove as much from result.json as possible in a way that still results in that error. I'd imagine you could just remove all but one messages from the file and it would still result in the same error

**Comment by vignakke** [comment]
i tried to remove like 480k and "only" 400k message (still 40k+ in the file but like this it's working)

**Comment by HopperElec** [comment]
Could you try removing all the messages except forsome going across the time change? Of course, you may want to obfuscate names and message content

**Comment by Laiteux** [comment]
Hello, encountering the exact same issue! Indeed seems related to summer/winter time change.

Can provide an export of around 1M Telegram messages from a private group I have with friends. Give me a few minutes, time to obfuscate it.

**Comment by HopperElec** [comment]
You shouldn't need to include all the messages to re-create the error, and so many messages will take some time to download. However, for future it might be a good idea to write a script which automatically obfuscates an exportso it's easier for samples to be provided for debugging and testing. I'll have a go at doing this later!

**Comment by Laiteux** [comment]
Sounds good!

Still, I'll include the whole 1M messages, because I remember some graphs not being generated (console error) even when I succeeded with the import. Would love to look into this with you as well.

**Comment by HopperElec** [comment]
Ah alright. I would make new issues for those then. On mobile right now so won't be able to have a good look until later, but once I can I'll be sure to!

**Comment by Laiteux** [comment]
Sure, will be happy to open a new issue after this one then! (as fixing this is basically a beforehand requirement)

**Comment by Laiteux** [comment]
https://www.sendspace.com/file/q5htyz

**Comment by Laiteux** [comment]
![msedge_sWojxFOjCh](https://user-images.githubusercontent.com/33204743/236627548-9b4c1e76-317a-4e47-a82e-683236377723.png)

**Comment by Laiteux** [comment]
Who should I send the file to? Don't feel like uploading it there. Any Telegram username I can contact you at? Mine is [@Matteo](https://t.me/Matteo)

**Comment by HopperElec** [comment]
Oh, I had already downloaded the original file, sorry. I don't have Telegram but if you would prefer I use the updated version you can contact me at any of these places https://www.hopperelec.co.uk/contact/

**Comment by HopperElec** [comment]
https://github.com/mlomb/chat-analytics/issues/79#issuecomment-1537138675
> You shouldn't need to include all the messages to re-create the error, and so many messages will take some time to download. However, for future it might be a good idea to write a script which automatically obfuscates an exportso it's easier for samples to be provided for debugging and testing. I'll have a go at doing this later!
I'ma work on this. Is this something that should be integrated into the repository in some way? If so, would it be a stand-alone file, would it be a part of the app or should it be a Jupyter Notebook (Python) so that it can be used straight from GitHub?

**Comment by mlomb** [comment]
Probably something like `https://chatanalytics.app/sample`. Making everything in plain JS in `assets/sample.html`
I think it would be the most simple and practical option

**Comment by mlomb** [comment]
Maybe `/obfuscate` or `/obfuscate_sample`, or something else. `sample` may be confused with a demo 😅

**Comment by Laiteux** [comment]
Edited my comment, sorry if it wasn't clear

**Comment by HopperElec** [comment]
So the file should be stand-alone but accessible via the app?

**Comment by mlomb** [comment]
> So the file should be stand-alone but accessible via the app?

Yup

**Comment by Kaputchino** [comment]
Is it normal that I still have this issue?

**Comment by HopperElec** [comment]
Yes, there has not yet been a good fix for this https://github.com/mlomb/chat-analytics/pull/80

**Comment by mlomb** [comment]
I have made some changes that I think will fix the issue in #80!

@Laiteux @Kaputchino can you your exports in https://pr-80.chat-analytics.pages.dev ?

**Comment by Kaputchino** [comment]
It's working just fine, thx.
