### ISSUE TITLE
Tool to obfuscate exports 

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#81]
Original mentioned in https://github.com/mlomb/chat-analytics/issues/79

It is often useful for people to share exports as a sample for testing or debugging Chat Analytics, however it can be tedious to obfuscate them to remove any personal data while keeping enough data for the report to appear realistic. There should be a tool which does this automatically, replacing any potentially personal information (message contents, IDs, author information, URLs) with gibberish (could just be some fixed text such as "REDACTED" or could be something like Lorem Ipsum). This tool should also compress the file to make it easier to share.

**Comment by HopperElec** [comment]
I'm not very good at design so I'm going to keep it intentionally minimal for someone else to improve. Not sure how important design even is for this page, since it's something few people will see.

**Comment by mlomb** [comment]
> I'm not very good at design so I'm going to keep it intentionally minimal for someone else to improve. Not sure how important design even is for this page, since it's something few people will see.

I expect this to be completely plain HTML and JS, no styles at all, just a select, file input and button, nothing fancy
This is a dev tool anyway

**Comment by HopperElec** [comment]
While this is a dev tool, I expect it will be primarily used by people reporting issues here, who could be ordinary users. Also, there will also need to be a selection (probably just a dropdown if we're using HTML forms) for which platform the export is from.

**Comment by Laiteux** [comment]
If you still wanna have it a little fancy then maybe just use the same form as the one to generate a report? Make it output an obfuscated file instead and boom, there you go.
