### ISSUE TITLE
"Error occurred, please check the console for more details" on some graphs

### ISSUE THREAD

**Issue by Laiteux** [mlomb/chat-analytics#85]
Exported 500K Telegram messages, Chat Anal worked fine. Tried with 1M from an other group so twice as much and now I'm getting some error:

https://github.com/mlomb/chat-analytics/assets/33204743/9d083506-60eb-4b75-a81d-3f893334060b

<details>
<summary>Messages -> Sentiment -> Timeline</summary>

![msedge_M6bW7i4ipd](https://github.com/mlomb/chat-analytics/assets/33204743/53a590f9-4839-410c-9c46-314938a69322)

![msedge_Nb3GeJH070](https://github.com/mlomb/chat-analytics/assets/33204743/8904016b-9288-4547-b6a2-f787d375e284)
</details>

**Comment by Laiteux** [comment]
Now that I'm thinking about it (not sure if it's related, haven't checked the code, just a random thought), couldn't it be because there was no message sent there since march 2022?

**Comment by mlomb** [comment]
> Now that I'm thinking about it (not sure if it's related, haven't checked the code, just a random thought), couldn't it be because there was no message sent there since march 2022?

Hmm that would be strange, it should not cause any problem

The obfuscator is not ready yet (hopefully I will get to it soon), so I don't know how to go around this one.
In the screenshot you posted, if you can place a breakpoint and print the variable `e` or `t` you will find the Database object, can you share the time part of it?

**Comment by Laiteux** [comment]
Sorry for the delay. Sure, here you go:

![msedge_d4D4mkocy2](https://github.com/mlomb/chat-analytics/assets/33204743/8d02b758-3ec5-4d00-a816-336934858367)

**Comment by mlomb** [comment]
It appears that everything is as it should.
I made a PR (#87) to print when indexing `dayIndex` above 850:

https://github.com/mlomb/chat-analytics/blob/544d6ac8c02da7dbae6ba2b2f6b1df75cd3388ce/pipeline/aggregate/blocks/messages/MessagesPerPeriod.ts#L48-L50


Can you share a screenshot of the console when exporting the chat from the PR? https://pr-87.chat-analytics.pages.dev

**Comment by Laiteux** [comment]
Sure, thank you

![msedge_Qzp5vHvbMu](https://github.com/mlomb/chat-analytics/assets/33204743/5fcc3eea-0c77-4af1-afa2-85cb3fffacb6)

**Comment by mlomb** [comment]
Interesting, the values from 851 to 860 are not printed and only one with 1023 is. Since the number of dayBits is 10, 1023 is the maximum, so all bits set.

I managed to track down the issue, it appears that the following `indexOf` is returning `-1`:
https://github.com/mlomb/chat-analytics/blob/65b524de49422a788aea567219793fb5edf3dfc4/pipeline/process/DatabaseBuilder.ts#L370

<details>
<summary>Details</summary>

I added `if (Math.random() < 0.1) msg.dayIndex = -1;` so it drops some messages and the same sections you show crash.

</details>

I added some logging for this too in the same PR, can you show me the console but now in the app (where you generate)? https://pr-87.chat-analytics.pages.dev

https://github.com/mlomb/chat-analytics/blob/a0df720971a02be294d5946e0c4450534625c408/pipeline/process/DatabaseBuilder.ts#L373-L382

**Comment by Laiteux** [comment]
Do I have to wait for it to be updated online?

**Comment by Laiteux** [comment]
Still doesn't work so I assume not

**Comment by mlomb** [comment]
Sorry for the delay I had to go!

It updates automatically on each commit, so its live 😄
Did you already tried and no log appeared?

**Comment by Laiteux** [comment]
Yep. Could you please try yourself? Or it is possible I might be doing this wrong as well.

**Comment by mlomb** [comment]
I checked the deploy and  the log is there 🤔. Maybe `dayIndex` is never `-1`.

What do you mean try yourself, is the server public?

I'll keep investigating

**Comment by Laiteux** [comment]
Well, this is what I have:

![sqqNGFvDO0](https://github.com/mlomb/chat-analytics/assets/33204743/20990dc2-ab59-4cdf-af1f-9e525485ac67)

**Comment by mlomb** [comment]
Thats the report UI! I mean the log when you generate the report (the app):

Here! (after completion)
![image](https://github.com/mlomb/chat-analytics/assets/5845105/ca0d4138-fb71-402a-a2e2-9f03f4e1be71)

**Comment by Laiteux** [comment]
Oh sorry, pretty sure I checked here too though. Let me check again.

**Comment by Laiteux** [comment]
![msedge_F5vSgQ0a2d](https://github.com/mlomb/chat-analytics/assets/33204743/6ae66ad4-dadf-4c44-b4c5-9c01be611116)

**Comment by mlomb** [comment]
Ok. So I added a check where dayIndex is created:

https://github.com/mlomb/chat-analytics/blob/e4e05cd30fc06db72ace433bc3fee86448417e30/pipeline/process/MessageProcessor.ts#L130-L153

Getting closer...
Now the error shuold come up in the generation UI

**Comment by Laiteux** [comment]
What are you calling the "generation UI"?

**Comment by Laiteux** [comment]
I don't see any error on the generation UI

**Comment by Laiteux** [comment]
![msedge_p79QeW8L4X](https://github.com/mlomb/chat-analytics/assets/33204743/6d21b0e9-faa9-4e65-b959-f1a1c377793f)

**Comment by mlomb** [comment]
Ok so the error does not happens there 🤔

**Comment by mlomb** [comment]
Just to confirm, this is still happening in v1.1.0? https://chatanalytics.app

**Comment by Laiteux** [comment]
Hey! It does.

**Comment by mlomb** [comment]
Aight
I think it is better to wait until #82 is done, since I can't fix it in the dark
I'll get to it when I have the time :)
Thanks for the patience

**Comment by mlomb** [comment]
Aaaaaaaaaaaaand we are back! #82 is ready
The tool to obfuscate reports is ready at https://chatanalytics.app/obfuscator.html Can you obfuscate your report (please audit the code / check the output) and share it? You can upload it here or you can send it by email 😄

**Comment by Laiteux** [comment]
Hey! Sent via email!

**Comment by mlomb** [comment]
I managed to replicate the issue! I'll update when I have fixed it!

Thanks!

**Comment by mlomb** [comment]
I... don't want to scare you... but... it may seem you have a time traveller in your group.
If you look at message #637699:
```json
{
  "id": 637699,
  "type": "message",
  "date": "2021-06-24T17:12:33",
  "edited": "2021-06-24T17:12:26",
  "from": "Wilbur Klein",
  "from_id": "7613595408",
  "text": "Terga.",
  "media_type": "animation",
  "mime_type": "video/mp4",
  "file": "(File not included. Change data exporting settings to download.)",
  "thumbnail": "(File not included. Change data exporting settings to download.)"
}
```

Somehow the `edited` timestamp is before `date`, causing `editedAfter` to be a negative number. `editerAfter` was being serialized with `writeVarInt` which does not support negative numbers, thus breaking serialization.

Anyway, the fix was adding the following line:
https://github.com/mlomb/chat-analytics/blob/33696f22ec24929008b08d4b285b619b600e54e0/pipeline/serialization/BitStream.ts#L129-L129

Thanks for taking the time to report this and waiting for the obfuscator! 🎊🎉 <sup>(and watch out for time distortion around your peers)</sup>

**Comment by Laiteux** [comment]
Amazing! Thank **you** for your time! Glad we were able to figure this out.

**Comment by HopperElec** [comment]
My guess is that someone with a poor connection was sending a message with an attachment and edited it before the attachment had finished sending so the "edit" request had finished before the original message was sent? Still woulda thought the platform would normalize it, though, lol

**Comment by Laiteux** [comment]
Editing a message while it's sending is not possible on Telegram, afaik

**Comment by HopperElec** [comment]
Oh. Well better keep the world updated on the actions of this time traveller you have discovered
