### ISSUE TITLE
Have the most common capitalization shown for top words

### ISSUE THREAD

**Issue by Laiteux** [mlomb/chat-analytics#86]
Wouldn't it make more sense to have the most common capitalization shown for top words instead of (I assume) the first occurrence it detected?

In my case, the only reason for this would be because it's the ~~only~~ _actually there are two_ top words shown capitalized, making them look just a little out of place next to the others:

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/mlomb/chat-analytics/assets/33204743/c051bc0e-9329-416e-81ae-f05783cd7ecd)
</details>

Or would that be too performance-intensive?

**Comment by mlomb** [comment]
Hi! Currently only the first occurence of a word is stored as you assumed.

<details>
<summary>How are words currently stored</summary>

We have a common interface that we use for multiple entities, the `IndexedMap`. Think of it like a map that also assigns a sequential index to each element:

https://github.com/mlomb/chat-analytics/blob/65b524de49422a788aea567219793fb5edf3dfc4/pipeline/process/DatabaseBuilder.ts#L30-L36



Each word (in its original casing) is processed by this function:

https://github.com/mlomb/chat-analytics/blob/65b524de49422a788aea567219793fb5edf3dfc4/pipeline/process/MessageProcessor.ts#L161-L174

As you can see, we add the word to the `IndexedMap` (`words.set(wordKey, this.forceStringCopy(word))`) using the lowercase version (among other things) of the word as key and the original as the value.

----

</details>

To change how it works, we should store every casing we've seen so far for each word and at the end keep the most common one. It is totally doable but we would have to make a more specialized `IndexedMap` and probably it will be very memory intensive.

I'll close as not planned for now but who knows 👀

**Comment by HopperElec** [comment]
For the time being, would it not be better to not store the capitalisation at all and just display them all in all-caps?

**Comment by Laiteux** [comment]
> For the time being, would it not be better to not store the capitalisation at all and just display them all in all-caps?

Sounds like a good idea. Or perhaps lowercase? Not sure what would make the most sense

**Comment by HopperElec** [comment]
I think upper-case because there's few cases where something is explicitly lowercase but plenty of cases where they're explicitly upper-case

**Comment by Laiteux** [comment]
Sounds fair (:
