### ISSUE TITLE
[Discord][Feature request] Show guild name next to channel name when multiple guilds are included in the report

### ISSUE THREAD

**Issue by HopperElec** [mlomb/chat-analytics#9]
I understand most users of chat-analytics are using it for researching an individual guild they own, but it is also really useful for people interested in researching themselves across guilds (the quantified self). Since this means including several guilds in the report, often which use many similar channel names (general, off-topic, vc-chat, chat-1, chat-2...), it can be hard to differentiate between some channels. If a user includes multiple guilds in a report, it would be useful to show the guild's name next to any listed channel names .

**Comment by mlomb** [comment]
Although I think this is a very niche feature, it can be nice to have
