### ISSUE TITLE
compile chat-analytics

### ISSUE THREAD

**Issue by ElegantPercentage** [mlomb/chat-analytics#90]
How do I compile this? I just want to generate the report using the command.

`npx chat-analytics -p discord -i "exported/*.json" -o report.html`

My *.json file is >2GB and I can't generate the file on your website.

**Comment by mlomb** [comment]
Hello!

JSON files over 2GB should be totally fine in the web app, can you tell me why you cant generate it using the app? (out of RAM?)

I tried the exact command you used and the report is being generated correctly both in Windows and Linux, are you using Mac?
Can you share the output you get?
