### ISSUE TITLE
About regular vs custom emojis

### ISSUE THREAD

**Issue by Laiteux** [mlomb/chat-analytics#91]
![msedge_bXTPjGYGN3](https://github.com/mlomb/chat-analytics/assets/33204743/c7701799-b0ac-4533-9bee-d8acb64f4f7a)

Shouldn't `:pepe:` be replaced by `:heart:` here, wouldn't that make more sense?

**Comment by Laiteux** [comment]
Same here, and then maybe in other places as well

![msedge_J8qjZGVe5U](https://github.com/mlomb/chat-analytics/assets/33204743/a67fb62e-3d98-412a-b1e2-aa9ace82323a)

**Comment by HopperElec** [comment]
No- :pepe: is to represent custom emojis, and the heart/fire are default so would not make sense there. Although I would say it could make sense to replace fire with hearts or replace the heart with fire.

**Comment by Laiteux** [comment]
Oh, it wasn't clear to me that this was supposed to represent custom emojis. Ok, guess it makes a lil more sense now.

**Comment by mlomb** [comment]
> it could make sense to replace fire with hearts or replace the heart with fire.

I agree. Since it is a very small change I'll slip it in the next update (whenever it may be).
I'll leave this open until then :)

**Comment by Laiteux** [comment]
thanks for using your brain when i couldn't.
